version: '3.1'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "{{ secrets_postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_name }}"

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
