services:
  postgresql:
    env_file:
      - compose_vars.env
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgresql"
