services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - compose_vars.env
    environment:
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    secrets:
      - postgres_password
    volumes: 
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgresql"

secrets:
  postgres_password:
    file: postgres_password.txt

volumes:
  db_data: #add later on
